"""Graph-guided evidence collection for wiki Q&A.

The chat endpoint previously used a fixed one-hop graph expansion.  This module
implements a controller-style loop:

1. map seed search hits to graph nodes;
2. inspect the adjacent typed edges and their evidence;
3. ask the LLM whether the current evidence is sufficient;
4. if not, expand only the most promising neighbouring pages;
5. repeat for at most two retrieval-control rounds.

The final answer is still generated by the existing chat prompt, so citations
and learner-profile behaviour remain unchanged.
"""

from __future__ import annotations

import asyncio
import json
import re
from collections import defaultdict
from dataclasses import dataclass, field

from services.graph_store import get_edges, get_nodes, make_node_id, record_exposure
from services.ingest_engine import _strip_images
from services.llm_client import chat_complete
from services.search_engine import _page_body
from storage.wiki_store import read_wiki_page


@dataclass
class GraphEvidence:
    """Result of iterative graph retrieval."""

    pages: list[dict] = field(default_factory=list)
    relations: list[dict] = field(default_factory=list)
    model_calls: int = 0
    rounds: int = 0
    sufficient: bool = False
    missing: list[str] = field(default_factory=list)


def _extract_json_object(text: str) -> dict:
    """Parse JSON from a model response, tolerating markdown fences."""
    if not text:
        return {}
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        value = json.loads(cleaned)
        return value if isinstance(value, dict) else {}
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{[\s\S]*\}", cleaned)
    if not match:
        return {}
    try:
        value = json.loads(match.group(0))
        return value if isinstance(value, dict) else {}
    except json.JSONDecodeError:
        return {}


def _priority(edge_type: str) -> int:
    """Favour pedagogically important edges when the controller is ambiguous."""
    order = {
        "prerequisite": 0,
        "teaches": 1,
        "enables": 2,
        "derives": 3,
        "applies_to": 4,
        "scaffolds": 5,
        "related": 6,
        "direct": 7,
        "source": 8,
    }
    return order.get(edge_type, 9)


def _node_path(node: dict) -> str:
    return str(node.get("page_path") or node.get("metadata", {}).get("path") or "")


def _shorten(text: str, limit: int) -> str:
    text = re.sub(r"\s+", " ", (text or "").strip())
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)].rstrip() + "…"


def _format_controller_prompt(
    query: str,
    pages: list[dict],
    frontier: list[dict],
    *,
    missing: list[str] | None = None,
) -> str:
    evidence_parts: list[str] = []
    for i, page in enumerate(pages, 1):
        evidence_parts.append(
            f"[{i}] {page.get('title', '')} ({page.get('path', '')})\n"
            f"Type: {page.get('node_type', 'unknown')}\n"
            f"Evidence: {_shorten(page.get('content', ''), 900)}"
        )

    frontier_parts: list[str] = []
    for candidate in frontier:
        edge = candidate.get("edge", {})
        relation = edge.get("edge_type", "related")
        evidence = edge.get("evidence") or edge.get("rationale") or ""
        frontier_parts.append(
            f"[{candidate['id']}] {candidate['title']} ({candidate['node_type']})\n"
            f"Relation: {relation} {edge.get('direction', 'linked')} "
            f"weight={edge.get('weight', 0):.2f}\n"
            f"Edge evidence: {_shorten(evidence, 240)}\n"
            f"Page preview: {_shorten(candidate.get('snippet', ''), 300)}"
        )

    missing_text = ""
    if missing:
        missing_text = "Previously missing aspects:\n- " + "\n- ".join(missing) + "\n"

    return f"""## User question
{query}

{missing_text}## Current evidence
{chr(10).join(evidence_parts) if evidence_parts else "(none)"}

## Candidate graph frontier
Each candidate is reached from evidence already selected. The relation and edge
evidence show why it is adjacent; the page preview shows what the neighbour says.

{chr(10).join(frontier_parts) if frontier_parts else "(no frontier)"}

## Task
Decide whether the current evidence is sufficient to answer all parts of the
question. If not, select at most four frontier nodes whose pages are likely to
provide the missing facts, definitions, formulas, mechanisms, contrasts, or
worked examples. Prefer prerequisite and mechanism edges when they explain the
question. Do not select pages merely because they are adjacent.

Return ONLY JSON:
{{"sufficient": false, "candidate_ids": ["id1"], "missing": ["one missing aspect"]}}
"""


def _relation_context(pages: list[dict], relations: list[dict]) -> str:
    if not relations:
        return ""
    page_number = {p["path"]: i for i, p in enumerate(pages, 1)}
    node_page = {p.get("node_id", ""): p["path"] for p in pages if p.get("node_id")}

    lines: list[str] = []
    for edge in relations:
        source = node_page.get(edge.get("source", ""), edge.get("source", ""))
        target = node_page.get(edge.get("target", ""), edge.get("target", ""))
        if source not in page_number or target not in page_number:
            continue
        relation = edge.get("edge_type", "related")
        evidence = edge.get("evidence") or edge.get("rationale") or ""
        line = (
            f"[{page_number[source]}] --{relation}--> [{page_number[target]}]"
        )
        if evidence:
            line += f": {_shorten(evidence, 300)}"
        lines.append(line)
    if not lines:
        return ""
    return "\n\n## Followed graph relations\n" + "\n".join(lines[:40])


async def collect_graph_evidence(
    query: str,
    seeds: list[dict],
    budget: dict,
    *,
    project_id: str = "default",
    user_id: str = "default",
    max_rounds: int = 2,
    max_expansions_per_round: int = 4,
) -> GraphEvidence:
    """Collect pages by graph-guided, LLM-controlled expansion.

    The function never raises for retrieval errors. If model calls fail, it
    falls back to deterministic high-weight expansion so chat remains usable.
    """
    page_budget = int(budget.get("page_budget", 20_000))
    max_page_size = int(budget.get("max_page_size", 5_000))
    used_chars = 0
    selected_pages: dict[str, dict] = {}
    selected_nodes: dict[str, dict] = {}
    used_relations: dict[tuple[str, str, str], dict] = {}
    result = GraphEvidence()

    nodes = get_nodes(project_id)
    if not nodes:
        try:
            from services.graph_engine import build_graph
            nodes = build_graph(project_id=project_id)["nodes"]
        except Exception:
            nodes = []
    nodes_by_id = {node["id"]: node for node in nodes}
    path_to_node = {
        _node_path(node): node["id"]
        for node in nodes
        if _node_path(node)
    }

    adjacency: dict[str, list[dict]] = defaultdict(list)
    for edge in get_edges(project_id):
        if float(edge.get("weight", 0) or 0) < 0.45:
            continue
        source = edge.get("source", "")
        target = edge.get("target", "")
        if source:
            adjacency[source].append({**edge, "direction": "→"})
        if target:
            adjacency[target].append({**edge, "direction": "←"})

    def add_page(
        path: str,
        title: str,
        *,
        node_id: str | None = None,
        node_type: str = "unknown",
        origin: str,
        priority: int,
        score: float = 0.0,
    ) -> bool:
        nonlocal used_chars
        if not path or path in selected_pages:
            return False
        try:
            page = read_wiki_page(path, project_id=project_id)
        except Exception:
            page = None
        raw_content = (page or {}).get("content", "") or _page_body(path, project_id=project_id)
        content = _strip_images(raw_content)
        if not content:
            return False

        limit = min(max_page_size, max(1, page_budget - used_chars))
        if len(content) > limit:
            content = content[:limit] + "\n\n[...truncated...]"
        if used_chars + len(content) > page_budget:
            return False

        used_chars += len(content)
        selected_pages[path] = {
            "path": path,
            "title": title or (page or {}).get("title") or path,
            "node_type": node_type,
            "content": content,
            "snippet": _shorten(content, 320),
            "priority": priority,
            "score": score,
            "origin": origin,
            "node_id": node_id or make_node_id(project_id, path),
        }
        if node_id:
            selected_nodes[node_id] = nodes_by_id.get(node_id, {"id": node_id})
        return True

    # Seed selection: explicit scope/title hits first, then ranked retrieval.
    ranked_seeds = sorted(
        seeds,
        key=lambda r: (0 if r.get("title_match") else 1, -float(r.get("score", 0) or 0)),
    )
    seed_limit = 8 if len(ranked_seeds) > 4 else max(len(ranked_seeds), 1)
    for seed in ranked_seeds[:seed_limit]:
        node_id = path_to_node.get(seed.get("path", ""))
        node = nodes_by_id.get(node_id or "", {})
        add_page(
            seed.get("path", ""),
            seed.get("title", ""),
            node_id=node_id,
            node_type=node.get("node_type", "unknown"),
            origin="seed",
            priority=0 if seed.get("title_match") else 1,
            score=float(seed.get("score", 0) or 0),
        )
        if used_chars >= page_budget:
            break

    def build_frontier() -> list[dict]:
        candidates: dict[str, dict] = {}
        for node_id in selected_nodes:
            for edge in adjacency.get(node_id, []):
                neighbor = edge.get("target") if edge.get("direction") == "→" else edge.get("source")
                if not neighbor or neighbor in selected_nodes:
                    continue
                node = nodes_by_id.get(neighbor)
                if not node:
                    continue
                path = _node_path(node)
                if not path or path in selected_pages:
                    continue
                key = f"edge:{edge.get('source', '')}->{edge.get('target', '')}:{edge.get('edge_type', '')}"
                candidate = {
                    "id": neighbor,
                    "key": key,
                    "node_id": neighbor,
                    "title": node.get("label") or node.get("title") or neighbor,
                    "node_type": node.get("node_type", "unknown"),
                    "path": path,
                    "edge": edge,
                    "snippet": _shorten(_page_body(path, project_id=project_id), 500),
                }
                old = candidates.get(neighbor)
                if old is None or (
                    float(edge.get("weight", 0) or 0),
                    -_priority(edge.get("edge_type", "")),
                ) > (
                    float(old["edge"].get("weight", 0) or 0),
                    -_priority(old["edge"].get("edge_type", "")),
                ):
                    candidates[neighbor] = candidate

        return sorted(
            candidates.values(),
            key=lambda c: (
                -float(c["edge"].get("weight", 0) or 0),
                _priority(c["edge"].get("edge_type", "")),
                c["title"],
            ),
        )[:36]

    controller_system = """You are the retrieval controller for a wiki-based educational question answering system.
You do not answer the user. You inspect already selected wiki evidence and a graph frontier of adjacent
knowledge nodes, then decide whether more evidence is required.

Rules:
- Sufficient means the evidence covers definitions, mechanisms, formulas, contrasts, examples, and prerequisites
  needed for a complete, well-cited answer.
- If insufficient, select only candidates that plausibly contain missing information.
- Prefer prerequisite, mechanism, derivation, and application edges over weak related edges.
- Do not select more than four nodes.
- Return only the requested JSON object.
"""

    missing: list[str] = []
    for round_number in range(1, max_rounds + 1):
        result.rounds = round_number
        frontier = build_frontier()
        if not frontier:
            break

        prompt = _format_controller_prompt(query, list(selected_pages.values()), frontier, missing=missing)
        try:
            raw = await chat_complete(
                system_prompt=controller_system,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=320,
                temperature=0.1,
                response_format={"type": "json_object"},
            )
            result.model_calls += 1
            decision = _extract_json_object(raw)
        except Exception:
            decision = {}

        candidate_ids = decision.get("candidate_ids", [])
        if not isinstance(candidate_ids, list):
            candidate_ids = []
        wanted = {str(value) for value in candidate_ids if str(value) in nodes_by_id}
        missing = [
            str(item)
            for item in (decision.get("missing", []) if isinstance(decision.get("missing", []), list) else [])
            if str(item).strip()
        ]
        result.missing = missing
        result.sufficient = bool(decision.get("sufficient")) and not wanted

        if result.sufficient or not wanted:
            # Model failure should not block retrieval: use the top weighted edge.
            if not result.model_calls:
                wanted = {frontier[0]["id"]}
            else:
                break

        selected_this_round: list[dict] = []
        for candidate_id in wanted:
            candidate = next((item for item in frontier if item["id"] == candidate_id), None)
            if not candidate:
                continue
            added = add_page(
                candidate["path"],
                candidate["title"],
                node_id=candidate["node_id"],
                node_type=candidate["node_type"],
                origin="graph",
                priority=2,
                score=float(candidate["edge"].get("weight", 0) or 0),
            )
            if added:
                selected_this_round.append(candidate)
                relation_key = (
                    candidate["edge"].get("source", ""),
                    candidate["edge"].get("target", ""),
                    candidate["edge"].get("edge_type", ""),
                )
                used_relations[relation_key] = candidate["edge"]
            if len(selected_this_round) >= max_expansions_per_round:
                break

        # Expose traversed nodes for learner analytics.
        try:
            for candidate in selected_this_round:
                record_exposure(project_id=project_id, user_id=user_id, node_id=candidate["node_id"])
        except Exception:
            pass

        if not selected_this_round or used_chars >= page_budget:
            break

    result.pages = list(selected_pages.values())
    result.relations = list(used_relations.values())
    return result
